Target  = test
Include = ../include ../3rd/xbin/src
Source  = $(shell find . -name "*.cpp")
LibDir  = ../lib ../3rd/xbin/lib
Lib     =
ObjDir  = ../obj
OutDir  = ../bin
Define  = _XOPEN_SOURCE
CFLAGS  =
CXXFLAGS =
LDFLAGS =
Rpath = ../lib

include ../utils/makefile