Package =
TargetType = x
Test = 1
Source = $(wildcard *.cpp)
Import = asyn box
ExportHeader =
Include =
Define = _XOPEN_SOURCE
CFLAGS =
CXXFLAGS = -std=c++14
LDFLAGS = -lpthread -ldl
Rpath =

include $(CPKG_PATH)/cmk
